name: Build our NixOS config
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
jobs:
  build_NixOS_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build
